Config = {}

Config.PoliceOpen = false -- Can Police open all stashes

Config.Stashes = {
    ["lspd armory"] = {
         stashName = "lspd armory",
         coords = vector3(455.93, -998.0, 35.06),
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "lspd",
         cid = {},  
         stashSize = 125000000,
         stashSlots = 150, 
     },
     ["bcso armory"] = {
        stashName = "bcso armory",
        coords = vector3(-1730.5, 358.6, 88.73), 
        requirecid = false,
        jobrequired = true,
        gangrequired = false,
        gang = "",
        job = "bcso",
        cid = {},  
        stashSize = 125000000,
        stashSlots = 150, 
    },
    ["noose armory"] = {
        stashName = "noose armory",
        coords = vector3(2528.07, -339.32, 101.89),
        requirecid = false,
        jobrequired = true,
        gangrequired = false,
        gang = "",
        job = "noose",
        cid = {},  
        stashSize = 125000000,
        stashSlots = 150, 
    },
    ["fib armory"] = {
        stashName = "fib armory",
        coords = vector3(153.34, -754.22, 45.75),
        requirecid = false,
        jobrequired = true,
        gangrequired = false,
        gang = "",
        job = "fib",
        cid = {},  
        stashSize = 125000000,
        stashSlots = 150, 
    },
    ["army armory"] = {
        stashName = "army armory",
        coords = vector3(-2358.7, 3254.56, 32.81),
        requirecid = false,
        jobrequired = true,
        gangrequired = false,
        gang = "",
        job = "army",
        cid = {},  
        stashSize = 125000000,
        stashSlots = 150, 
    },
    ["exotics stash"] = {
        stashName = "exotics stash",
        coords = vector3(922.20, -953.15, 39.50),
        requirecid = false,
        jobrequired = true,
        gangrequired = false,
        gang = "",
        job = "exotics",
        cid = {},  
        stashSize = 125000000,
        stashSlots = 150, 
    },
}